I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 84, in script
    if has_dragon:
  File "game/script.rpy", line 84, in <module>
    if has_dragon:
NameError: name 'has_dragon' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 84, in script
    if has_dragon:
  File "C:\Users\drapt\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\drapt\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\drapt\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 84, in <module>
    if has_dragon:
NameError: name 'has_dragon' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Visual Novel Project 1.0
Sat Feb 25 00:29:41 2023
